openapi: 3.0.1
info:
  title: Qoissant API
  description: This is a server which provides a question and answer service. Post
    a question, or get answers to previously asked questions.
  version: 0.0.1
servers:
- url: /swagger
tags:
- name: question
  description: A question for Qoissant
- name: answer
  description: An answer to a question
paths:
  /questions:
    post:
      tags:
      - question
      summary: Add a question to Qoissant
      operationId: addQuestion
      requestBody:
        description: A question to add to Qoissant
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
        required: true
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  /answers:
    get:
      tags:
      - answer
      summary: Finds answers by query
      description: Provide a query and get matching answers
      operationId: findAnswersByQuery
      parameters:
      - name: query
        in: query
        description: a search query
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'
        400:
          description: Invalid status value
          content: {}
components:
  schemas:
    Question:
      required:
      - text
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
          example: Where was the croissant invented?
    Answer:
      required:
      - text
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
          example: Austria
